
#define TRANSACTION_SUBMISSION_PORT "9012"

#define SERVER_CONTROL_PORT "9013"
#define BLOCK_FORWARDING_PORT "9014"
#define BLOCK_CONFIRMATION_PORT "9015"
#define FORWARDING_REQUEST_PORT "9016"

#define HOTSTUFF_BLOCK_FETCH_PORT "9017"
